# Generated by Django 4.2.2 on 2023-07-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='author',
        ),
    ]
