# Generated by Django 4.2.2 on 2023-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_messages_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
